using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace TelnetNegotiationCore.SourceGenerators;

/// <summary>
/// Source generator that creates fast, reflection-free extension methods for enums.
/// Generates AllValues collections and IsDefined methods to replace Enum.GetValues() and Enum.IsDefined().
/// </summary>
[Generator]
public class EnumExtensionsGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Create a provider for enum declarations
        var enumProvider = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => s is EnumDeclarationSyntax e && 
                    (e.Identifier.Text == "Trigger" || e.Identifier.Text == "State"),
                transform: static (ctx, _) => GetEnumSymbol(ctx))
            .Where(static m => m is not null);

        // Generate source for each enum
        context.RegisterSourceOutput(enumProvider, (spc, enumSymbol) =>
        {
            if (enumSymbol == null) return;

            var enumName = enumSymbol.Name;
            var generateBadStateMethod = enumName == "State";
            var source = GenerateEnumExtensions(enumSymbol, enumName, generateBadStateMethod);
            spc.AddSource($"{enumName}Extensions.g.cs", SourceText.From(source, Encoding.UTF8));
        });
    }

    private static INamedTypeSymbol? GetEnumSymbol(GeneratorSyntaxContext context)
    {
        var enumDecl = (EnumDeclarationSyntax)context.Node;
        var symbol = context.SemanticModel.GetDeclaredSymbol(enumDecl) as INamedTypeSymbol;
        
        if (symbol?.TypeKind == TypeKind.Enum && 
            (symbol.Name == "Trigger" || symbol.Name == "State"))
        {
            return symbol;
        }
        
        return null;
    }

    private static string GenerateEnumExtensions(INamedTypeSymbol enumSymbol, string enumName, bool generateBadStateMethod = false)
    {
        var namespaceName = enumSymbol.ContainingNamespace.ToDisplayString();
        var values = enumSymbol.GetMembers()
            .OfType<IFieldSymbol>()
            .Where(f => f.IsConst)
            .ToList();

        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Collections.Immutable;");
        sb.AppendLine($"using {namespaceName};");
        sb.AppendLine();
        sb.AppendLine("namespace TelnetNegotiationCore.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Generated extension methods for {enumName} enum - replaces reflection with compile-time code.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public static class {enumName}Extensions");
        sb.AppendLine("{");

        // Generate AllValues property
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// All {enumName} values (generated at compile time).");
        sb.AppendLine($"    /// Replaces: Enum.GetValues(typeof({enumName}))");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    public static readonly ImmutableHashSet<{enumName}> AllValues = ImmutableHashSet.Create(");

        for (int i = 0; i < values.Count; i++)
        {
            var value = values[i];
            var comma = i < values.Count - 1 ? "," : "";
            sb.AppendLine($"        {enumName}.{value.Name}{comma}");
        }

        sb.AppendLine("    );");
        sb.AppendLine();

        // Generate IsDefined method
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Fast validation without reflection.");
        sb.AppendLine($"    /// Replaces: Enum.IsDefined(typeof({enumName}), value)");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    public static bool IsDefined(short value) => value switch");
        sb.AppendLine("    {");

        // Deduplicate by value to avoid unreachable patterns
        var seenValues = new HashSet<object>();
        foreach (var value in values)
        {
            var constantValue = value.ConstantValue;
            if (constantValue != null && seenValues.Add(constantValue))
            {
                sb.AppendLine($"        {constantValue} => true,  // {value.Name}");
            }
        }

        sb.AppendLine("        _ => false");
        sb.AppendLine("    };");

        // Generate GetBadState method if requested (only for State enum)
        if (generateBadStateMethod)
        {
            sb.AppendLine();
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// Get 'Bad' state variant for error handling.");
            sb.AppendLine("    /// Replaces: (State)Enum.Parse(typeof(State), $\"Bad{state}\")");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static State GetBadState(State state) => state switch");
            sb.AppendLine("    {");

            // Find all "Bad" states by looking for enum values that start with "Bad"
            var badStateMappings = new List<(string normalState, string badState)>();
            foreach (var value in values)
            {
                if (value.Name.StartsWith("Bad") && value.Name.Length > 3)
                {
                    var normalStateName = value.Name.Substring(3); // Remove "Bad" prefix
                    // Check if the normal state exists
                    if (values.Any(v => v.Name == normalStateName))
                    {
                        badStateMappings.Add((normalStateName, value.Name));
                    }
                }
            }

            foreach (var (normalState, badState) in badStateMappings)
            {
                sb.AppendLine($"        State.{normalState} => State.{badState},");
            }

            sb.AppendLine("        _ => throw new ArgumentException($\"No Bad state exists for {state}\", nameof(state))");
            sb.AppendLine("    };");
        }

        sb.AppendLine("}");

        return sb.ToString();
    }
}
