using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace TelnetNegotiationCore.SourceGenerators;

/// <summary>
/// Source generator that creates compile-time property accessors for MSSPConfig
/// to replace runtime reflection with generated code.
/// </summary>
[Generator]
public class MSSPConfigGenerator : ISourceGenerator
{
    public void Initialize(GeneratorInitializationContext context)
    {
        // Register a syntax receiver to find MSSPConfig class
        context.RegisterForSyntaxNotifications(() => new MSSPSyntaxReceiver());
    }

    public void Execute(GeneratorExecutionContext context)
    {
        if (context.SyntaxReceiver is not MSSPSyntaxReceiver receiver)
            return;

        // Find MSSPConfig class in the compilation
        INamedTypeSymbol? msspConfigClass = null;
        foreach (var classDecl in receiver.CandidateClasses)
        {
            var semanticModel = context.Compilation.GetSemanticModel(classDecl.SyntaxTree);
            var symbol = semanticModel.GetDeclaredSymbol(classDecl) as INamedTypeSymbol;
            if (symbol?.Name == "MSSPConfig")
            {
                msspConfigClass = symbol;
                break;
            }
        }

        if (msspConfigClass == null)
            return; // MSSPConfig not found in this compilation

        // Extract properties with [Name] attribute
        var properties = ExtractMSSPProperties(msspConfigClass);

        if (properties.Count == 0)
            return;

        // Generate the accessor class
        var sourceText = GenerateMSSPAccessor(properties);

        // Add the generated source to the compilation
        context.AddSource("MSSPConfigAccessor.g.cs", SourceText.From(sourceText, Encoding.UTF8));
    }

    private List<MSSPPropertyInfo> ExtractMSSPProperties(INamedTypeSymbol msspConfigClass)
    {
        var properties = new List<MSSPPropertyInfo>();

        foreach (var member in msspConfigClass.GetMembers().OfType<IPropertySymbol>())
        {
            // Find [Name] attribute
            var nameAttribute = member.GetAttributes()
                .FirstOrDefault(a => a.AttributeClass?.Name == "NameAttribute");

            if (nameAttribute == null)
                continue;

            // Extract attribute arguments
            var msspName = nameAttribute.ConstructorArguments.FirstOrDefault().Value?.ToString() ?? member.Name;
            
            var officialAttribute = member.GetAttributes()
                .FirstOrDefault(a => a.AttributeClass?.Name == "OfficialAttribute");
            var isOfficial = officialAttribute?.ConstructorArguments.FirstOrDefault().Value as bool? ?? false;

            properties.Add(new MSSPPropertyInfo(
                propertyName: member.Name,
                msspName: msspName,
                propertyType: member.Type.ToDisplayString(),
                isOfficial: isOfficial
            ));
        }

        return properties;
    }

    private string GenerateMSSPAccessor(List<MSSPPropertyInfo> properties)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Globalization;");
        sb.AppendLine("using TelnetNegotiationCore.Models;");
        sb.AppendLine();
        sb.AppendLine("namespace TelnetNegotiationCore.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Generated MSSP configuration accessor - replaces reflection with compile-time code.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class MSSPConfigAccessor");
        sb.AppendLine("{");

        // Generate property map
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Pre-computed mapping of MSSP variable names to property metadata.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static readonly IReadOnlyDictionary<string, MSSPPropertyMetadata> PropertyMap = new Dictionary<string, MSSPPropertyMetadata>");
        sb.AppendLine("    {");
        
        foreach (var prop in properties)
        {
            sb.AppendLine($"        [\"{Canonicalize(prop.MSSPName)}\"] = new(\"{prop.PropertyName}\", \"{prop.PropertyType}\", {prop.IsOfficial.ToString().ToLowerInvariant()}),");
        }
        
        sb.AppendLine("    };");
        sb.AppendLine();

        // Generate TrySetValues method - the primary binder, taking every value MSSP reported
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Binds every value MSSP reported for a variable onto the matching property (zero reflection).");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <remarks>");
        sb.AppendLine("    /// A variable may carry several values. List-typed properties take all of them in wire order;");
        sb.AppendLine("    /// scalar properties take the last, which the specification defines as the default value.");
        sb.AppendLine("    /// The name is canonicalized first, so the specification's recommended underscore-for-space");
        sb.AppendLine("    /// substitution (<c>CRAWL_DELAY</c>) binds the same as the spaced spelling.");
        sb.AppendLine("    /// </remarks>");
        sb.AppendLine("    public static bool TrySetValues(MSSPConfig config, string msspVariableName, IReadOnlyList<string> values)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (config == null) throw new ArgumentNullException(nameof(config));");
        sb.AppendLine("        if (values == null || values.Count == 0) return false;");
        sb.AppendLine();
        sb.AppendLine("        return MSSPVariables.Canonicalize(msspVariableName) switch");
        sb.AppendLine("        {");

        foreach (var prop in properties)
        {
            sb.AppendLine($"            \"{Canonicalize(prop.MSSPName)}\" => TrySet_{prop.PropertyName}(config, values),");
        }

        sb.AppendLine("            _ => false");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Generate TrySetProperty method
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Sets a property value by MSSP variable name using generated code (zero reflection).");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <remarks>Converts <paramref name=\"value\"/> to its MSSP wire form and defers to <see cref=\"TrySetValues\"/>.</remarks>");
        sb.AppendLine("    public static bool TrySetProperty(MSSPConfig config, string msspVariableName, object? value)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (config == null) throw new ArgumentNullException(nameof(config));");
        sb.AppendLine("        if (value == null) return false;");
        sb.AppendLine();
        sb.AppendLine("        return TrySetValues(config, msspVariableName, ToWireValues(value));");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private static IReadOnlyList<string> ToWireValues(object value)");
        sb.AppendLine("    {");
        sb.AppendLine("        switch (value)");
        sb.AppendLine("        {");
        sb.AppendLine("            case string text:");
        sb.AppendLine("                return new[] { text };");
        sb.AppendLine("            case bool flag:");
        sb.AppendLine("                return new[] { flag ? \"1\" : \"0\" };");
        sb.AppendLine("            case System.Collections.IEnumerable items:");
        sb.AppendLine("            {");
        sb.AppendLine("                var list = new List<string>();");
        sb.AppendLine("                foreach (var item in items) list.Add(item?.ToString() ?? string.Empty);");
        sb.AppendLine("                return list;");
        sb.AppendLine("            }");
        sb.AppendLine("            default:");
        sb.AppendLine("                return new[] { System.Convert.ToString(value, CultureInfo.InvariantCulture) ?? string.Empty };");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Generate individual setter methods
        foreach (var prop in properties)
        {
            GenerateSetterMethod(sb, prop);
        }

        sb.AppendLine("}");
        sb.AppendLine();

        // Generate metadata record
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Metadata about an MSSP property.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public record MSSPPropertyMetadata(string PropertyName, string PropertyType, bool IsOfficial);");

        return sb.ToString();
    }

    private void GenerateSetterMethod(StringBuilder sb, MSSPPropertyInfo prop)
    {
        sb.AppendLine($"    private static bool TrySet_{prop.PropertyName}(MSSPConfig config, IReadOnlyList<string> values)");
        sb.AppendLine("    {");

        // Generate type-specific conversion logic. Scalars take the last value, which the MSSP
        // specification defines as the default; list-typed properties take every value in order.
        if (prop.PropertyType == "string" || prop.PropertyType == "string?")
        {
            sb.AppendLine("        config." + prop.PropertyName + " = values[values.Count - 1];");
            sb.AppendLine("        return true;");
        }
        else if (prop.PropertyType == "int" || prop.PropertyType == "int?")
        {
            sb.AppendLine("        if (int.TryParse(values[values.Count - 1], NumberStyles.Integer, CultureInfo.InvariantCulture, out var parsed))");
            sb.AppendLine("        {");
            sb.AppendLine("            config." + prop.PropertyName + " = parsed;");
            sb.AppendLine("            return true;");
            sb.AppendLine("        }");
            sb.AppendLine("        return false;");
        }
        else if (prop.PropertyType == "bool" || prop.PropertyType == "bool?")
        {
            sb.AppendLine("        if (MSSPValue.TryParseFlag(values[values.Count - 1], out var flag))");
            sb.AppendLine("        {");
            sb.AppendLine("            config." + prop.PropertyName + " = flag;");
            sb.AppendLine("            return true;");
            sb.AppendLine("        }");
            sb.AppendLine("        return false;");
        }
        else if (prop.PropertyType.Contains("IEnumerable"))
        {
            sb.AppendLine("        var all = new string[values.Count];");
            sb.AppendLine("        for (var i = 0; i < values.Count; i++) all[i] = values[i];");
            sb.AppendLine("        config." + prop.PropertyName + " = all;");
            sb.AppendLine("        return true;");
        }
        else
        {
            sb.AppendLine("        // Type not supported for auto-generation: " + prop.PropertyType);
            sb.AppendLine("        return false;");
        }

        sb.AppendLine("    }");
        sb.AppendLine();
    }

    /// <summary>
    /// The canonical spelling of an MSSP variable name, mirroring
    /// <c>TelnetNegotiationCore.Models.MSSPVariables.Canonicalize</c>: upper case, underscores folded
    /// to spaces, whitespace runs collapsed. Applied at generation time so the emitted switch labels
    /// match what that method produces at runtime.
    /// </summary>
    private static string Canonicalize(string variable)
    {
        var folded = new StringBuilder(variable.Length);
        var pendingSpace = false;

        foreach (var character in variable)
        {
            var c = character == '_' ? ' ' : character;

            if (char.IsWhiteSpace(c))
            {
                pendingSpace = folded.Length > 0;
                continue;
            }

            if (pendingSpace)
            {
                folded.Append(' ');
                pendingSpace = false;
            }

            folded.Append(char.ToUpperInvariant(c));
        }

        return folded.ToString();
    }

    private class MSSPPropertyInfo
    {
        public string PropertyName { get; }
        public string MSSPName { get; }
        public string PropertyType { get; }
        public bool IsOfficial { get; }

        public MSSPPropertyInfo(string propertyName, string msspName, string propertyType, bool isOfficial)
        {
            PropertyName = propertyName;
            MSSPName = msspName;
            PropertyType = propertyType;
            IsOfficial = isOfficial;
        }
    }
}

/// <summary>
/// Syntax receiver that collects candidate class declarations
/// </summary>
internal class MSSPSyntaxReceiver : ISyntaxReceiver
{
    public List<ClassDeclarationSyntax> CandidateClasses { get; } = new();

    public void OnVisitSyntaxNode(SyntaxNode syntaxNode)
    {
        // Look for classes named MSSPConfig
        if (syntaxNode is ClassDeclarationSyntax classDecl 
            && classDecl.Identifier.Text == "MSSPConfig")
        {
            CandidateClasses.Add(classDecl);
        }
    }
}
